
# html lang
language: zh-CN

# header
site_brand_name: BY HUANG.

menu:
  Home: /
  Archive: /archives/
  Gallery: /categories/gallery/
  About: /about/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/frame.js

# favicon
favicon: /favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: BY HUANG. 
  body: Blog By Huang.
  image: /profile_cover.png

  links:
    Home: /
    Blogs: /archives/
    About: /about/

# footer
footer:
  copyright_info:
    enable: false
    author:

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: false
    content:

# color mode: default / classic / dark
color_mode: classic

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: true
